### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by vbarboza6** [teamjalopy/pond#28]
- [ ] Find viable template engine and agree on it
- [ ] Generate sitewide header and footer

**Comment by phrz** [comment]
Although we're using Angular for the app itself, the landing page and even the app pages can have common assets.

**Comment by phrz** [comment]
This issue is not [currently] relevant as a design decision, according to team consensus. On the client, Angular Views will be used as a quasi-templating system, aside from that, no major/robust PHP template engine need be used.
