### ISSUE TITLE
Lesson API

### ISSUE THREAD

**Issue by geffgant** [teamjalopy/pond#38]
- [x] Create Eloquent Model `Lesson` and define relations with `User` models for creator, etc. (refer to data model)
- [x] Add route for `GET /lessons`
- [x] Add route for `POST /lessons`
- [x] Add route for `GET /lessons/{lesson_id}`
- [x] Add route for `PUT /lessons/{lesson_id}`
- [x] Add route for `DELETE /lessons/{lesson_id}`

**Comment by phrz** [comment]
Reassigned to prevent issue stagnation

**Comment by phrz** [comment]
Fixed with open PR #67
